### ISSUE TITLE
Fix exception in retract_antenna

### ISSUE THREAD

**Issue by sei-jvessella** [cmu-sei/gamebrain#74]
```
2023-11-06T15:23:25-05:00	ERROR:    Exception in ASGI application
2023-11-06T15:23:25-05:00	Traceback (most recent call last):
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
2023-11-06T15:23:25-05:00	    result = await app(self.scope, self.receive, self.send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2023-11-06T15:23:25-05:00	    return await self.app(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
2023-11-06T15:23:25-05:00	    await super().__call__(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-11-06T15:23:25-05:00	    await self.middleware_stack(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-06T15:23:25-05:00	    raise exc
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-06T15:23:25-05:00	    await self.app(scope, receive, _send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
2023-11-06T15:23:25-05:00	    raise exc
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
2023-11-06T15:23:25-05:00	    await self.app(scope, receive, sender)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-11-06T15:23:25-05:00	    raise e
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-11-06T15:23:25-05:00	    await self.app(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
2023-11-06T15:23:25-05:00	    await route.handle(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
2023-11-06T15:23:25-05:00	    await self.app(scope, receive, send)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-11-06T15:23:25-05:00	    response = await func(request)
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
2023-11-06T15:23:25-05:00	    raw_response = await run_endpoint_function(
2023-11-06T15:23:25-05:00	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2023-11-06T15:23:25-05:00	    return await dependant.call(**values)
2023-11-06T15:23:25-05:00	  File "/app/./gamebrain/gamedata/controller.py", line 119, in get_retractantenna
2023-11-06T15:23:25-05:00	    result = await GameStateManager.retract_antenna(team_id)
2023-11-06T15:23:25-05:00	  File "/app/./gamebrain/gamedata/cache.py", line 2122, in retract_antenna
2023-11-06T15:23:25-05:00	    if team_data.session.pc4Game:
2023-11-06T15:23:25-05:00	AttributeError: 'SessionDataTeamSpecific' object has no attribute 'pc4Game'
```

**Comment by sei-jvessella** [comment]
Fixed in 99c6847ea6fc818949ad08ea70c45fa5e4ef4018
